# ================================
# Nombre de la aplicación
# ================================
spring.application.name=SafeCity - Backend

# ================================
# Profile activo por defecto
# ================================
spring.profiles.active=dev

# ================================
# Configuración de Swagger/OpenAPI
# ================================
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ================================
# Configuración de Jackson (fechas)
# ================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Bogota

# ================================
# Prefix para API
# ================================
server.servlet.context-path=/api
